# NOTE: ip_addressに登録するサーバには事前にisuconユーザでsshできるようにしておく

host01:
  hostname:   isucon-01
  ip_address: isucon-01
host02:
  hostname:   isucon-02
  ip_address: isucon-02
host03:
  hostname:   isucon-03
  ip_address: isucon-03
